/**
 * Emits supabase/migrations/0004_demo_data.sql from the same seedDataset() the
 * local mock adapter uses, so the live database and local dev show identical
 * demo content.
 *
 * Run:  npx vite-node scripts/genDemoSql.ts
 *
 * The seed's profile ids ('u-anadya') are placeholders — profiles.id is a UUID
 * that must reference auth.users. Real auth UUIDs are substituted here.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { seedDataset, AN, RG } from '../src/data/seed';
import type { Dataset } from '../src/types';

// Real auth.users UUIDs from the live project.
const UUID = {
  [AN]: '6929a827-f871-4c9a-b6bb-367b823b16b3',
  [RG]: '78e2346f-632f-4928-aeb7-857ec7b751bf',
} as const;
const TEST_UUID = '00000000-0000-4000-8000-000000000001';
const TEST_EMAIL = 'test@orra.ops';

const lit = (v: unknown): string => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  if (Array.isArray(v)) {
    if (v.length === 0) return `'{}'`;
    // text[] for tags; JSONB for object arrays
    if (v.every((x) => typeof x === 'string')) {
      return `ARRAY[${v.map((x) => lit(x)).join(',')}]::text[]`;
    }
    return `${lit(JSON.stringify(v))}::jsonb`;
  }
  if (typeof v === 'object') return `${lit(JSON.stringify(v))}::jsonb`;
  let s = String(v);
  // Map placeholder profile ids onto real auth UUIDs.
  for (const [placeholder, uuid] of Object.entries(UUID)) {
    if (s === placeholder) s = uuid;
  }
  return `'${s.replace(/'/g, "''")}'`;
};

const insert = (table: string, rows: Record<string, unknown>[], conflict = 'id'): string => {
  if (!rows.length) return '';
  const cols = Object.keys(rows[0]).filter((c) => c !== 'password' && c !== 'data_url');
  const values = rows
    .map((r) => `  (${cols.map((c) => lit(r[c])).join(', ')})`)
    .join(',\n');
  return `INSERT INTO public.${table} (${cols.join(', ')}) VALUES\n${values}\nON CONFLICT (${conflict}) DO NOTHING;\n`;
};

const ds: Dataset = seedDataset();

const parts: string[] = [];
parts.push(`-- Demo data — generated by scripts/genDemoSql.ts. Do not hand-edit.
-- Safe to re-run: every statement is ON CONFLICT DO NOTHING.
--
-- Creates a third TEST account (${TEST_EMAIL}) alongside the two real members.
-- CLAUDE.md says the product will never have a third *user*; this is a test
-- fixture for verifying the app, not a member — delete it with the block at
-- the bottom of this file when you no longer need it.
`);

// ── test account ──────────────────────────────────────────────────────
parts.push(`-- ═══ Test account ═══════════════════════════════════════════════════
-- The allowlist row must exist first: the enforce_allowlist trigger on
-- auth.users rejects any address that isn't allowlisted.
INSERT INTO public.allowlist (email, name, role)
VALUES ('${TEST_EMAIL}', 'Test', 'member')
ON CONFLICT (email) DO NOTHING;

-- The token columns MUST be '' and not NULL. Supabase's auth service scans
-- them as strings, and a NULL makes every sign-in fail with the opaque
-- "Database error querying schema" — which looks like a schema problem but is
-- really this row. The dashboard's own "Add user" sets them to ''.
INSERT INTO auth.users (
  id, instance_id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  raw_app_meta_data, raw_user_meta_data,
  confirmation_token, recovery_token,
  email_change, email_change_token_new, email_change_token_current,
  phone_change, phone_change_token, reauthentication_token
) VALUES (
  '${TEST_UUID}', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
  '${TEST_EMAIL}', extensions.crypt('Test@2026', extensions.gen_salt('bf')),
  now(), now(), now(),
  '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb,
  '', '', '', '', '', '', '', ''
) ON CONFLICT (id) DO NOTHING;

-- Repair any auth row (this one or a hand-made one) that has NULL tokens.
UPDATE auth.users SET
  confirmation_token = COALESCE(confirmation_token, ''),
  recovery_token = COALESCE(recovery_token, ''),
  email_change = COALESCE(email_change, ''),
  email_change_token_new = COALESCE(email_change_token_new, ''),
  email_change_token_current = COALESCE(email_change_token_current, ''),
  phone_change = COALESCE(phone_change, ''),
  phone_change_token = COALESCE(phone_change_token, ''),
  reauthentication_token = COALESCE(reauthentication_token, '');

-- Password grant needs a matching identity row.
INSERT INTO auth.identities (
  id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
) VALUES (
  gen_random_uuid(), '${TEST_UUID}', '${TEST_UUID}',
  ('{"sub":"${TEST_UUID}","email":"${TEST_EMAIL}","email_verified":true}')::jsonb,
  'email', now(), now(), now()
) ON CONFLICT (provider, provider_id) DO NOTHING;
`);

// ── profiles (real UUIDs; the provision trigger may already have made them) ──
const profiles = ds.profiles.map((p) => ({
  ...p,
  id: UUID[p.id as keyof typeof UUID] ?? p.id,
}));
profiles.push({
  ...ds.profiles[0],
  id: TEST_UUID,
  email: TEST_EMAIL,
  name: 'Test',
  time_zone: 'Asia/Kolkata',
  status_text: 'Kicking the tyres',
} as (typeof profiles)[number]);
parts.push(`-- ═══ Profiles ═══════════════════════════════════════════════════════`);
parts.push(insert('profiles', profiles as unknown as Record<string, unknown>[]));

// ── the rest of the dataset ───────────────────────────────────────────
const TABLES: (keyof Dataset)[] = [
  'projects',
  'tags',
  'objectives',
  'key_results',
  'tasks',
  'subtasks',
  'comments',
  'screenshot_attachments',
  'annotation_pins',
  'decisions',
  'notes',
  'mail_items',
  'documents',
  'people',
  'people_interactions',
  'messages',
  'shared_daily',
  'courses',
  'course_items',
  'reading_queue',
  'time_logs',
  'life_admin',
  'fixed_dates',
  'ledger',
  'audit_trail',
  'automation_rules',
  'daily_closeouts',
  'day_events',
];

parts.push(`-- ═══ Demo content ═══════════════════════════════════════════════════`);
for (const t of TABLES) {
  const rows = ds[t] as unknown as Record<string, unknown>[];
  if (!Array.isArray(rows) || !rows.length) continue;
  parts.push(insert(t, rows));
}

parts.push(`
-- ═══ Removing the test account later ════════════════════════════════
-- DELETE FROM auth.users WHERE email = '${TEST_EMAIL}';
-- DELETE FROM public.allowlist WHERE email = '${TEST_EMAIL}';
`);

mkdirSync('supabase/migrations', { recursive: true });
writeFileSync('supabase/migrations/0004_demo_data.sql', parts.filter(Boolean).join('\n'));
console.log('wrote supabase/migrations/0004_demo_data.sql');
