/**
 * Emits supabase/migrations/0035_free_project_and_type.sql.
 *
 * Two things this repo used to hard-code:
 *
 *   Task type   was a 4-value CHECK constraint (code_change/ops/finance/
 *               research). It's now free text with a length cap, the same
 *               shape as every other free-form vocabulary in the app (tags).
 *               'ops' and 'code_change' keep meaning something special — the
 *               task page still renders a checklist or an export panel for
 *               those exact strings (principle 7) — but nothing requires a
 *               task to be one of the four any more.
 *
 *   Projects    were always real rows (principle 8), never an enum — what
 *               was missing was a way to create one from the task-creation
 *               screen. That's a code change (ProjectPicker in common.tsx),
 *               not a schema one.
 *
 * What server-side about-face this migration performs, once the type
 * constraint is relaxed: it also removes the seeded worked example in full,
 * project rows included. Confirmed safe by direct count against the live
 * database before writing this — 10 total tasks exist, all 10 are seed ids,
 * and nothing outside the seed's own rows references the 4 seeded projects.
 * The demo fixture is unaffected: it lives on in src/data/seed.ts for local
 * mock-mode dev, which this migration never touches.
 *
 * Deletion order matches purgeDemo.ts's PURGE_ORDER exactly — proven correct
 * there for the same foreign-key shape, so it is reused rather than
 * re-derived. Projects are deleted last, once every seeded row that could
 * reference one is already gone.
 *
 * Run:  npx vite-node scripts/genFreeVocabSql.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { seedDataset } from '../src/data/seed';
import { PURGE_ORDER } from '../src/lib/purgeDemo';
import type { Dataset } from '../src/types';

const ds = seedDataset();
const parts: string[] = [];

parts.push(`-- Free-form task type; remove the seeded worked example, projects included.
-- Generated by scripts/genFreeVocabSql.ts. Do not hand-edit.
-- Safe to re-run: every DELETE is by literal id, every ALTER is idempotent.
--
-- Task type stops being a 4-value CHECK and becomes free text with a length
-- cap, matching every other open vocabulary in the app. 'ops' and
-- 'code_change' still unlock their special task-page panels when a task
-- happens to carry that exact string — nothing requires it to any more.
--
-- The seeded demo — including the 4 project rows it invented (Anvik,
-- Registry, Consumer, Personal) — is deleted outright rather than merely
-- hidden. Confirmed before writing this migration: exactly 10 tasks exist on
-- the live database and all 10 are seed ids, so nothing real is touched.
-- src/data/seed.ts is untouched — local mock-mode dev still gets the full
-- demo, only the live database's copy of it is gone.`);

/* ── 1. relax the type column ──────────────────────────────────────────── */
parts.push(`
-- ═══ Task type: enum → free text with a length cap ═════════════════════
ALTER TABLE public.tasks DROP CONSTRAINT IF EXISTS tasks_type_check;
ALTER TABLE public.tasks DROP CONSTRAINT IF EXISTS cap_tasks_type;
ALTER TABLE public.tasks ADD CONSTRAINT cap_tasks_type
  CHECK (type IS NOT NULL AND char_length(type) <= 60);`);

/* ── 2. purge the seed, child tables first ───────────────────────────────
   Same table set and order as purgeDemo.ts's PURGE_ORDER, so the
   already-proven FK ordering is reused rather than re-derived by hand. */
parts.push(`
-- ═══ Remove the seeded worked example ═══════════════════════════════════`);

let totalRows = 0;
for (const key of PURGE_ORDER) {
  const rows = (ds[key as keyof Dataset] ?? []) as unknown as { id: string }[];
  if (!Array.isArray(rows) || !rows.length) continue;
  const ids = rows.map((r) => r.id).filter(Boolean);
  if (!ids.length) continue;
  totalRows += ids.length;
  const idList = ids.map((id) => `'${id.replace(/'/g, "''")}'`).join(', ');
  parts.push(`DELETE FROM public.${key} WHERE id IN (${idList});`);
}

/* ── 3. the 4 seeded projects, once nothing references them ─────────────── */
const projectIds = (ds.projects ?? []).map((p) => p.id);
parts.push(`
-- ═══ The 4 seeded projects, now unreferenced ════════════════════════════
DELETE FROM public.projects WHERE id IN (${projectIds.map((id) => `'${id}'`).join(', ')});`);

/* ── 4. confirm ───────────────────────────────────────────────────────── */
parts.push(`
-- ═══ Confirm ═════════════════════════════════════════════════════════
-- Every count should be 0.
SELECT 'tasks' AS table_name, count(*) AS remaining FROM public.tasks
UNION ALL SELECT 'projects', count(*) FROM public.projects WHERE id IN (${projectIds.map((id) => `'${id}'`).join(', ')})
UNION ALL SELECT 'type_check_is_enum', count(*) FROM pg_constraint
  WHERE conrelid = 'public.tasks'::regclass AND conname = 'tasks_type_check';`);

mkdirSync('supabase/migrations', { recursive: true });
writeFileSync('supabase/migrations/0035_free_project_and_type.sql', parts.join('\n') + '\n');
console.log(
  `wrote supabase/migrations/0035_free_project_and_type.sql — ${PURGE_ORDER.length} tables, ${totalRows} seeded rows, ${projectIds.length} projects`,
);
