/**
 * Emits supabase/migrations/0034_demo_off_real_profiles.sql — moves every
 * seeded row off Anadya's and Raghuvar's profiles and onto the test account.
 *
 * Why this is needed at all. 0004 created the worked example attributed to
 * the two real profiles. 0011 was written to fix that, and generates the same
 * rows attributed to test@anvik.ops — but every statement in it is
 * `ON CONFLICT (id) DO NOTHING`, and 0004 had already inserted those exact
 * ids. So against a database that had run 0004, 0011 was a no-op: the rows
 * kept their real-profile attribution. `withoutDemo()` hides them from the
 * two members at the app layer, which is why nobody noticed — but the data
 * is still there, and still says Anadya created a task she never created.
 *
 * This migration fixes the data instead of the view. It only ever re-points
 * the columns that name a person; the rows themselves, their ids and their
 * content are untouched, so the demo stays intact under the test account and
 * Admin → Data's "Remove demo content" still finds it by id.
 *
 * What decides a row is demo: `seedDataset()` IS the manifest, the same rule
 * purgeDemo.ts uses. Ids are enumerated literally — there is no pattern match
 * and no date heuristic, so a row created in the app can never be caught by
 * this, whatever it is called. Real ids are timestamp-based (`c-mfk3j2x1`),
 * seeded ones are literals (`c-1`), and only the literal list is written out.
 *
 * Run:  npx vite-node scripts/genReattributeSql.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { seedDataset } from '../src/data/seed';
import type { Dataset } from '../src/types';

/** Real auth.users UUIDs from the live project (see 0004_demo_data.sql). */
const AN_UUID = '6929a827-f871-4c9a-b6bb-367b823b16b3';
const RG_UUID = '78e2346f-632f-4928-aeb7-857ec7b751bf';
const TEST_UUID = '00000000-0000-4000-8000-000000000001';
const TEST_EMAIL = 'test@anvik.ops';

/**
 * Every column that names a person, per table, derived from the schema's
 * `REFERENCES public.profiles` declarations.
 *
 * Deliberately absent:
 *  - `audit_trail`, `personal_order_events` — UPDATE is revoked at the
 *    database (principle 4). The trail is allowed to say a real person did
 *    something, because at the time the row was written that is what it
 *    recorded; rewriting history is the one thing it exists to prevent.
 *  - `integration_grants` — a live Google connection, not seeded content.
 *  - `profiles` — the three people themselves are structure, not demo.
 */
const PERSON_COLUMNS: Partial<Record<keyof Dataset, string[]>> = {
  tasks: ['created_by', 'assignee_id'],
  subtasks: [],
  comments: ['author_id'],
  screenshot_attachments: ['uploaded_by'],
  annotation_pins: ['author_id'],
  task_links: ['created_by'],
  decisions: ['owner_id'],
  notes: ['created_by', 'owner_id'],
  mail_items: ['owner_id'],
  documents: ['owner_id'],
  pages: ['created_by', 'last_edited_by', 'owner_id'],
  page_comments: ['author_id', 'resolved_by'],
  page_revisions: ['author_id'],
  people_interactions: ['logged_by'],
  messages: ['sender_id'],
  shared_daily: ['picked_by'],
  courses: ['owner_id'],
  reading_queue: ['owner_id'],
  time_logs: ['user_id'],
  life_admin: ['user_id'],
  fixed_dates: ['owner_id'],
  ledger: ['paid_by'],
  import_batches: ['imported_by'],
  daily_closeouts: ['user_id'],
  day_plans: ['user_id'],
  day_plan_items: ['user_id'],
  day_events: ['user_id'],
  active_blocks: ['user_id'],
  personal_goals: ['user_id'],
  personal_orders: ['user_id', 'reviewed_by'],
  mood_items: ['user_id'],
  subscriptions: ['paid_by'],
  tags: ['created_by'],
};

const sq = (v: string) => `'${v.replace(/'/g, "''")}'`;

/** Chunked so no single statement carries an unreasonable id list. */
function idList(ids: string[]): string {
  return ids.map(sq).join(', ');
}

const ds = seedDataset();
const parts: string[] = [];

parts.push(`-- Move the worked example off the two real profiles.
-- Generated by scripts/genReattributeSql.ts. Do not hand-edit.
-- Safe to re-run: every statement is an idempotent UPDATE.
--
-- 0004 attributed the demo content to Anadya and Raghuvar. 0011 was meant to
-- correct that, but its inserts are ON CONFLICT (id) DO NOTHING and 0004 had
-- already claimed those ids — so on any database that ran 0004, 0011 changed
-- nothing and the rows still name a real person as their author. The app
-- hides them from both members (src/lib/demoScope.ts), so this was invisible
-- rather than absent.
--
-- This re-points only the columns that name a person. Row ids and content are
-- untouched, so the demo stays whole under test@anvik.ops and the existing
-- "Remove demo content" purge still matches it by id.
--
-- Scope: the ids below come from seedDataset(), the same manifest purgeDemo.ts
-- uses. Nothing you created in the app can be caught by this — real ids are
-- timestamp-based, these are the seed's literals.
--
-- audit_trail is deliberately NOT rewritten: UPDATE is revoked on it, and a
-- trail that can be retroactively re-attributed is not a trail.`);

let statements = 0;
let rowsCovered = 0;

for (const [table, cols] of Object.entries(PERSON_COLUMNS) as [keyof Dataset, string[]][]) {
  if (!cols.length) continue;
  const rows = (ds[table] ?? []) as unknown as { id: string }[];
  if (!Array.isArray(rows) || !rows.length) continue;

  const ids = rows.map((r) => r.id).filter(Boolean);
  if (!ids.length) continue;

  const sets = cols
    .map((c) => `      ${c} = CASE WHEN ${c} IN ('${AN_UUID}', '${RG_UUID}') THEN '${TEST_UUID}'::uuid ELSE ${c} END`)
    .join(',\n');

  const guard = cols.map((c) => `${c} IN ('${AN_UUID}', '${RG_UUID}')`).join('\n         OR ');

  parts.push(`
-- ${table}: ${ids.length} seeded row${ids.length === 1 ? '' : 's'}
UPDATE public.${table} SET
${sets}
 WHERE id IN (${idList(ids)})
   AND (${guard});`);

  statements += 1;
  rowsCovered += ids.length;
}

/* Demo mail sat on a real inbox address, which is the most visibly wrong of
   the lot — it put mail nobody received above mail they did. */
const mailIds = (ds.mail_items ?? []).map((m) => m.id);
if (mailIds.length) {
  parts.push(`
-- The demo mail also carried a real account address on it.
UPDATE public.mail_items
   SET account_email = ${sq(TEST_EMAIL)}
 WHERE id IN (${idList(mailIds)})
   AND account_email IN ('anvik.anadya@gmail.com', 'raghuvar.anvik@gmail.com');`);
}

parts.push(`
-- ═══ Confirm ══════════════════════════════════════════════════════════
-- Every count should be 0. Anything above 0 is a seeded row still naming a
-- real person, and means this migration did not cover that column.
SELECT 'tasks' AS table_name, count(*) AS still_real FROM public.tasks
 WHERE id IN (${idList((ds.tasks ?? []).map((t) => t.id))})
   AND (created_by IN ('${AN_UUID}', '${RG_UUID}') OR assignee_id IN ('${AN_UUID}', '${RG_UUID}'))
UNION ALL
SELECT 'notes', count(*) FROM public.notes
 WHERE id IN (${idList((ds.notes ?? []).map((n) => n.id))})
   AND (created_by IN ('${AN_UUID}', '${RG_UUID}') OR owner_id IN ('${AN_UUID}', '${RG_UUID}'))
UNION ALL
SELECT 'mail_items', count(*) FROM public.mail_items
 WHERE id IN (${idList(mailIds)})
   AND (owner_id IN ('${AN_UUID}', '${RG_UUID}')
        OR account_email IN ('anvik.anadya@gmail.com', 'raghuvar.anvik@gmail.com'));`);

mkdirSync('supabase/migrations', { recursive: true });
writeFileSync('supabase/migrations/0034_demo_off_real_profiles.sql', parts.join('\n') + '\n');
console.log(
  `wrote supabase/migrations/0034_demo_off_real_profiles.sql — ${statements} tables, ${rowsCovered} seeded rows`,
);
