/**
 * Emits supabase/migrations/0011_test_demo_data.sql — a worked example
 * attributed entirely to the test@orra.ops account, not to Anadya or
 * Raghuvar's real profiles.
 *
 * Why a separate generator instead of reusing genDemoSql.ts: the original
 * demo set attributed every row to the two real profiles ("a person you
 * never met should not sit in People" — src/lib/purgeDemo.ts), which is
 * exactly the confusion this one avoids. Same seedDataset() manifest, same
 * ids (so the existing "Remove demo content" purge — which matches by seed
 * id, not by owner — still finds and removes these), but every AN/RG
 * attribution is redirected to the test account instead of a real one.
 *
 * Run:  npx vite-node scripts/genTestDemoSql.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { seedDataset, AN, RG } from '../src/data/seed';
import type { Dataset } from '../src/types';

// Real auth.users UUIDs from the live project — profiles table only.
const UUID = {
  [AN]: '6929a827-f871-4c9a-b6bb-367b823b16b3',
  [RG]: '78e2346f-632f-4928-aeb7-857ec7b751bf',
} as const;
const TEST_UUID = '00000000-0000-4000-8000-000000000001';
const TEST_EMAIL = 'test@orra.ops';

// Exact-match substitutions applied to every table except `profiles`, so
// every content row reads as the test account's, not a real person's.
const REDIRECT: Record<string, string> = {
  [AN]: TEST_UUID,
  [RG]: TEST_UUID,
  Anadya: 'Test',
  Raghuvar: 'Test',
  'anvik.anadya@gmail.com': TEST_EMAIL,
  'raghuvar.anvik@gmail.com': TEST_EMAIL,
};

/** Deep-walk a row, replacing only exact whole-value matches (never substrings). */
function redirect<T>(v: T): T {
  if (typeof v === 'string') return (REDIRECT[v] ?? v) as unknown as T;
  if (Array.isArray(v)) return v.map(redirect) as unknown as T;
  if (v && typeof v === 'object') {
    return Object.fromEntries(Object.entries(v).map(([k, val]) => [k, redirect(val)])) as T;
  }
  return v;
}

const lit = (v: unknown): string => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  if (Array.isArray(v)) {
    if (v.length === 0) return `'{}'`;
    if (v.every((x) => typeof x === 'string')) {
      return `ARRAY[${v.map((x) => lit(x)).join(',')}]::text[]`;
    }
    return `${lit(JSON.stringify(v))}::jsonb`;
  }
  if (typeof v === 'object') return `${lit(JSON.stringify(v))}::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const insert = (table: string, rows: Record<string, unknown>[], conflict = 'id'): string => {
  if (!rows.length) return '';
  const cols = Object.keys(rows[0]).filter((c) => c !== 'password' && c !== 'data_url');
  const values = rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(', ')})`).join(',\n');
  return `INSERT INTO public.${table} (${cols.join(', ')}) VALUES\n${values}\nON CONFLICT (${conflict}) DO NOTHING;\n`;
};

const ds: Dataset = seedDataset();

const parts: string[] = [];
parts.push(`-- Test-only demo data — generated by scripts/genTestDemoSql.ts. Do not hand-edit.
-- Safe to re-run: every statement is ON CONFLICT DO NOTHING.
--
-- Same worked example as 0004, but attributed entirely to test@orra.ops
-- instead of Anadya and Raghuvar's real profiles — see purgeDemo.ts's own
-- complaint about the original: "a person you never met should not sit in
-- People, and a mail you never received should not sit above your real
-- inbox." Uses the same seeded ids, so Admin -> Data's "Remove demo
-- content" (which matches by id, not by owner) still finds and clears it.
--
-- Assumes 0004 already created the test@orra.ops auth user, allowlist row,
-- and the three profiles — this migration only re-adds content, redirected.
`);

const TABLES: (keyof Dataset)[] = [
  // objectives/key_results before tasks — tasks.objective_id has no cascade,
  // and purgeDemo.ts's PURGE_ORDER treats these as content (unlike projects
  // and sprints), so they were removed along with everything else and need
  // to come back before anything can reference them.
  'objectives',
  'key_results',
  'tags',
  'tasks',
  'subtasks',
  'comments',
  'screenshot_attachments',
  'annotation_pins',
  'decisions',
  'notes',
  'mail_items',
  'documents',
  'people',
  'people_interactions',
  'messages',
  'shared_daily',
  'courses',
  'course_items',
  'reading_queue',
  'time_logs',
  'life_admin',
  'fixed_dates',
  'ledger',
  'audit_trail',
  'automation_rules',
  'daily_closeouts',
  'day_events',
];

parts.push(`-- ═══ Demo content, attributed to test@orra.ops ═══════════════════════`);
for (const t of TABLES) {
  const rows = (ds[t] as unknown as Record<string, unknown>[]).map(redirect);
  if (!Array.isArray(rows) || !rows.length) continue;
  parts.push(insert(t, rows));
}

mkdirSync('supabase/migrations', { recursive: true });
writeFileSync('supabase/migrations/0011_test_demo_data.sql', parts.filter(Boolean).join('\n'));
console.log('wrote supabase/migrations/0011_test_demo_data.sql');
