-- Test-only demo data — generated by scripts/genTestDemoSql.ts. Do not hand-edit.
-- Safe to re-run: every statement is ON CONFLICT DO NOTHING.
--
-- Same worked example as 0004, but attributed entirely to test@anvik.ops
-- instead of Anadya and Raghuvar's real profiles — see purgeDemo.ts's own
-- complaint about the original: "a person you never met should not sit in
-- People, and a mail you never received should not sit above your real
-- inbox." Uses the same seeded ids, so Admin -> Data's "Remove demo
-- content" (which matches by id, not by owner) still finds and clears it.
--
-- Assumes 0004 already created the test@anvik.ops auth user, allowlist row,
-- and the three profiles — this migration only re-adds content, redirected.

-- ═══ Demo content, attributed to test@anvik.ops ═══════════════════════
INSERT INTO public.objectives (id, title, project_id, quarter, created_at) VALUES
  ('okr-reg', 'Registry spine complete', 'reg', 'Q3', '2026-07-01T09:00:00+05:30'),
  ('okr-score', 'Scoring engine production-ready', 'anvik', 'Q3', '2026-07-01T09:00:00+05:30'),
  ('okr-con', 'Consumer venture validated', 'con', 'Q3', '2026-07-10T09:00:00+05:30'),
  ('okr-italy', 'Land in Italy, settled', 'personal', 'Q3', '2026-07-01T09:00:00+05:30')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.key_results (id, objective_id, title, progress_pct, position) VALUES
  ('kr-1', 'okr-reg', 'Collectors live in production', 72, 1),
  ('kr-2', 'okr-reg', 'Entity resolution above 95%', 88, 2),
  ('kr-3', 'okr-reg', 'Publishability policy signed off', 40, 3),
  ('kr-4', 'okr-score', 'v3.8 frozen and regressed', 62, 1),
  ('kr-5', 'okr-score', 'Two pilots scored end to end', 35, 2),
  ('kr-6', 'okr-con', 'Two vendor quotes landed', 50, 1),
  ('kr-7', 'okr-con', '50 pre-orders', 12, 2),
  ('kr-8', 'okr-italy', 'Visa and permesso done', 30, 1),
  ('kr-9', 'okr-italy', 'Housing secured', 0, 2),
  ('kr-10', 'okr-italy', 'Week-1 reading finished', 15, 3)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tags (id, name, color, created_by, created_at) VALUES
  ('tag-1', 'urgent-path', 'rose', '00000000-0000-4000-8000-000000000001', '2026-07-01T09:00:00+05:30'),
  ('tag-2', 'blocked', 'stamp', '00000000-0000-4000-8000-000000000001', '2026-07-01T09:00:00+05:30'),
  ('tag-3', 'needs-raghuvar', 'teal', '00000000-0000-4000-8000-000000000001', '2026-07-02T09:00:00+05:30'),
  ('tag-4', 'investor-facing', 'indigo', '00000000-0000-4000-8000-000000000001', '2026-07-05T09:00:00+05:30'),
  ('tag-5', 'visa', 'sky', '00000000-0000-4000-8000-000000000001', '2026-07-08T09:00:00+05:30'),
  ('tag-6', 'quick-win', 'teal', '00000000-0000-4000-8000-000000000001', '2026-07-11T09:00:00+05:30')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tasks (id, title, description, acceptance_criteria, project_id, type, status, priority, assignee_id, created_by, start_date, due_date, objective_id, tags, progress_pct, effort, estimate_minutes, impact, is_stuck, blocked_reason, sprint_id, board_order, created_at, updated_at) VALUES
  ('T-47', 'Rain-gear vendor shortlist', 'Two quotes in hand, one pending. Decide before the sample run.', '', 'con', 'ops', 'todo', 'normal', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', '2026-08-18', '2026-08-21', 'okr-con', ARRAY['needs-raghuvar']::text[], 10, 'light', 25, 2, false, NULL, 'sprint-1', 0, '2026-08-14T10:00:00+05:30', '2026-08-17T10:00:00+05:30'),
  ('T-46', 'IBBI collector — retry backoff', '', '', 'reg', 'code_change', 'todo', 'normal', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', '2026-08-19', '2026-08-22', 'okr-reg', '{}', 5, 'medium', 50, 3, false, NULL, 'sprint-1', 0, '2026-08-14T11:00:00+05:30', '2026-08-16T11:00:00+05:30'),
  ('T-45', 'AnvikSure v3.8 fixture regression', 'Regress the full fixture set before the version is frozen.', '- Full fixture set green
- No score drift beyond 0.5% on golden cases', 'anvik', 'code_change', 'in_progress', 'urgent', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', '2026-08-15', '2026-08-18', 'okr-score', ARRAY['urgent-path']::text[], 62, 'heavy', 90, 5, false, NULL, 'sprint-1', 0, '2026-08-12T09:00:00+05:30', '2026-08-17T18:00:00+05:30'),
  ('T-44', 'Samadhaan collector — queue reorder', '', '', 'reg', 'code_change', 'in_progress', 'high', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', '2026-08-14', '2026-08-19', 'okr-reg', ARRAY['blocked']::text[], 44, 'medium', 55, 4, false, 'Needs fixture confirmation from Anadya', 'sprint-1', 0, '2026-08-11T09:00:00+05:30', '2026-08-17T09:00:00+05:30'),
  ('T-42', 'eCourts collector — QA report', 'Parser output diverges from the portal on pre-2019 case records. Evidence pinned below; verify against the DDL fixture before closing.', '- Pre-2019 records parse to the same fields the portal shows
- Karnataka bench legacy format covered by a fixture
- QA report attached to the task', 'reg', 'code_change', 'in_review', 'urgent', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', '2026-08-16', '2026-08-20', 'okr-reg', ARRAY['urgent-path']::text[], 80, 'medium', 70, 5, false, NULL, 'sprint-1', 0, '2026-08-10T09:00:00+05:30', '2026-08-17T09:14:00+05:30'),
  ('T-41', 'Visa appointment — Milan consulate', 'Slot booking opens 8am. Documents checklist in Knowledge.', '', 'personal', 'ops', 'in_progress', 'urgent', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', '2026-08-17', '2026-08-20', 'okr-italy', ARRAY['visa']::text[], 30, 'light', 20, 5, false, NULL, 'sprint-1', 0, '2026-08-09T09:00:00+05:30', '2026-08-17T08:00:00+05:30'),
  ('T-40', 'Read: attention paper set, week 1', '', '', 'personal', 'research', 'todo', 'normal', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', '2026-08-19', '2026-08-23', 'okr-italy', '{}', 0, 'heavy', 80, 2, false, NULL, 'sprint-1', 0, '2026-08-08T09:00:00+05:30', '2026-08-08T09:00:00+05:30'),
  ('T-38', 'Tighten SEO copy on anvik.club', '', '', 'anvik', 'ops', 'todo', 'low', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', '2026-08-22', '2026-08-24', NULL, ARRAY['quick-win']::text[], 0, 'light', 30, 1, false, NULL, 'sprint-1', 0, '2026-08-07T09:00:00+05:30', '2026-08-07T09:00:00+05:30'),
  ('T-36', 'Investor one-pager — traction numbers', '', '', 'anvik', 'ops', 'todo', 'high', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', '2026-08-21', '2026-08-26', 'okr-score', ARRAY['investor-facing']::text[], 0, 'medium', 60, 4, false, NULL, 'sprint-1', 0, '2026-08-05T09:00:00+05:30', '2026-08-05T09:00:00+05:30'),
  ('T-30', 'MCA collector — entity resolution', '', '', 'reg', 'code_change', 'done', 'normal', '00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', '2026-08-10', '2026-08-14', 'okr-reg', '{}', 100, 'medium', 45, 3, false, NULL, 'sprint-1', 0, '2026-08-01T09:00:00+05:30', '2026-08-14T17:00:00+05:30')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.subtasks (id, task_id, title, completed, position) VALUES
  ('st-1', 'T-42', 'Rerun parser on DDL fixture', true, 1),
  ('st-2', 'T-42', 'Diff against portal HTML capture', true, 2),
  ('st-3', 'T-42', 'Write QA summary note', false, 3),
  ('st-4', 'T-47', 'Ask Surat for revised MOQ', true, 1),
  ('st-5', 'T-47', 'Compare landed cost with duty', false, 2),
  ('st-6', 'T-41', 'Book the 8am slot', false, 1),
  ('st-7', 'T-41', 'Print bank statements', true, 2)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.comments (id, task_id, author_id, body, is_decision, created_at) VALUES
  ('c-1', 'T-42', '00000000-0000-4000-8000-000000000001', 'Pinned the two divergent regions on the grid screenshot. The date column shifts by one on pre-2019 rows.', false, '2026-08-17T09:14:00+05:30'),
  ('c-2', 'T-42', '00000000-0000-4000-8000-000000000001', 'Treat pre-2019 as its own parser branch — do not patch the main path.', true, '2026-08-17T10:02:00+05:30'),
  ('c-3', 'T-45', '00000000-0000-4000-8000-000000000001', 'Golden cases 12 and 31 drifted 0.7% — inspecting before freeze.', false, '2026-08-17T16:40:00+05:30')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.screenshot_attachments (id, task_id, storage_path, filename, mime, width, height, uploaded_by, created_at) VALUES
  ('shot-1', 'T-42', 'screenshots/T-42/samadhaan_grid.png', 'samadhaan_grid.png', 'image/png', 1440, 900, '00000000-0000-4000-8000-000000000001', '2026-08-17T09:10:00+05:30')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.annotation_pins (id, screenshot_id, x_pct, y_pct, note, label, author_id, is_resolved, created_at) VALUES
  ('pin-1', 'shot-1', 32.4, 41, 'Date column shifted one cell left on pre-2019 rows', 'bug', '00000000-0000-4000-8000-000000000001', false, '2026-08-17T09:12:00+05:30'),
  ('pin-2', 'shot-1', 71.8, 63.5, 'Case number truncated at 16 chars — NIC widens to 24 on 1 Sept', 'logic', '00000000-0000-4000-8000-000000000001', false, '2026-08-17T09:14:00+05:30')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.decisions (id, question, project_id, recommendation, owner_id, status, opened_at, ruled_at, ruling_note) VALUES
  ('dec-1', 'Company rename — Trazio or stay Anvik?', 'anvik', 'Trazio — cleanest uncontested candidate on screening.', '00000000-0000-4000-8000-000000000001', 'open', '2026-06-02T09:00:00+05:30', NULL, ''),
  ('dec-2', 'Pricing metric — per verification or per seat?', 'anvik', 'Per verification. Seats punish the behaviour we want.', '00000000-0000-4000-8000-000000000001', 'open', '2026-08-11T09:00:00+05:30', NULL, ''),
  ('dec-3', 'Shell detection — hard gate or penalty tier?', 'anvik', 'Binary hard gate.', '00000000-0000-4000-8000-000000000001', 'ruled', '2026-08-02T09:00:00+05:30', '2026-08-14T09:00:00+05:30', 'Binary hard gate. Revisit only if false positives cross 2%.'),
  ('dec-4', 'Rain gear — Ludhiana or Surat for the sample run?', 'con', 'Wait for Surat revision, decide Friday.', '00000000-0000-4000-8000-000000000001', 'open', '2026-08-15T09:00:00+05:30', NULL, '')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.notes (id, title, body, type, project_id, task_id, tags, is_pinned, transcript, checklist, source_ref, created_by, created_at) VALUES
  ('n-1', 'Vendor call — rain gear', 'Ludhiana quotes ₹340/unit at 500 MOQ, 50% advance. Surat pending.', 'voice', 'con', 'T-47', ARRAY['needs-raghuvar']::text[], false, '[{"at":"00:41","text":"Ludhiana can do 340 a unit but only at 500 minimum."},{"at":"06:12","text":"Half in advance, half on dispatch."},{"at":"11:03","text":"Surat will revise by Friday."}]'::jsonb, '[{"text":"Ask Surat for revised MOQ","done":true},{"text":"Compare landed cost with duty","done":false}]'::jsonb, 'plaud:rec-2026-08-17-0730', '00000000-0000-4000-8000-000000000001', '2026-08-17T07:30:00+05:30'),
  ('n-2', 'Parser edge cases', 'Pre-2019 eCourts records use two legacy formats. A third appears only in Karnataka benches.', 'plain', 'reg', 'T-42', '{}', true, NULL, NULL, NULL, '00000000-0000-4000-8000-000000000001', '2026-08-17T11:00:00+05:30'),
  ('n-3', 'Decision — scoring floor', 'Shell detection stays a binary hard gate. Revisit only if false positives cross 2%.', 'plain', 'anvik', NULL, '{}', false, NULL, NULL, NULL, '00000000-0000-4000-8000-000000000001', '2026-08-14T09:30:00+05:30'),
  ('n-4', 'Weekly — three commitments', '', 'meeting', 'anvik', NULL, '{}', false, NULL, '[{"text":"Ship the export engine","done":true},{"text":"Close two registry collectors","done":false},{"text":"Decide the company name","done":false}]'::jsonb, NULL, '00000000-0000-4000-8000-000000000001', '2026-08-11T09:00:00+05:30'),
  ('n-5', 'From mail — NIC cutover', 'Case-number field widens to 24 chars on 1 Sept.', 'email', 'reg', 'T-42', '{}', false, NULL, NULL, 'gmail:msg-nic-2026-08-17', '00000000-0000-4000-8000-000000000001', '2026-08-17T09:12:00+05:30'),
  ('n-6', 'Walking note — pricing', 'Value metric should be per verification, not per seat.', 'voice', 'anvik', NULL, '{}', false, '[{"at":"02:20","text":"Charge for the thing they value: a verified counterparty."}]'::jsonb, NULL, 'plaud:rec-2026-08-12-1815', '00000000-0000-4000-8000-000000000001', '2026-08-12T18:15:00+05:30')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.mail_items (id, account_email, sender, subject, snippet, received_at, gmail_link, flag_reason, project_id, converted_to_type, converted_to_id) VALUES
  ('m-1', 'test@anvik.ops', 'NIC eCourts', 'Change notice — case number field', 'Case-number field widens to 24 chars effective 1 September.', '2026-08-17T09:05:00+05:30', 'https://mail.google.com/mail/u/0/#inbox', 'deadline 1 Sept detected', 'reg', 'note', 'n-5'),
  ('m-2', 'test@anvik.ops', 'Milan consulate', 'Appointment window opens Monday 8:00', 'Study-visa slots for September intake open Monday 8:00 CET.', '2026-08-16T17:20:00+05:30', 'https://mail.google.com/mail/u/0/#inbox', 'appointment window', 'personal', NULL, NULL),
  ('m-3', 'test@anvik.ops', 'Surat Textiles', 'Revised quote by Friday', 'We will revise the MOQ and unit price by Friday EOD.', '2026-08-15T14:00:00+05:30', 'https://mail.google.com/mail/u/1/#inbox', NULL, 'con', NULL, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.documents (id, title, project_id, expiry_date, deadline_note, cloud_ref_url, status_cache) VALUES
  ('doc-1', 'Passport', 'personal', '2029-03-14', '', 'https://drive.google.com/', 'ok'),
  ('doc-2', 'Schengen study visa', 'personal', NULL, 'pending decision', 'https://drive.google.com/', 'soon'),
  ('doc-3', 'Permesso di soggiorno', 'personal', NULL, 'within 8 days of arrival', 'https://drive.google.com/', 'over'),
  ('doc-4', 'Health insurance — Italy', 'personal', '2026-08-31', '', 'https://drive.google.com/', 'soon'),
  ('doc-5', 'Incorporation certificate', 'anvik', NULL, '', 'https://drive.google.com/', 'ok'),
  ('doc-6', 'Founders agreement', 'anvik', '2027-01-01', 'renews 1 Jan 2027', 'https://drive.google.com/', 'ok'),
  ('doc-7', 'University enrolment letter', 'personal', '2026-08-25', 'upload by 25 Aug', 'https://drive.google.com/', 'soon'),
  ('doc-8', 'GST registration', 'anvik', NULL, '', 'https://drive.google.com/', 'ok')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.people (id, name, role, relationship_type, project_id, time_zone, cadence_days, last_contact_date, next_action, notes, created_at) VALUES
  ('p-1', 'Ludhiana Steel', 'Pilot customer', 'customer', 'anvik', 'Asia/Kolkata', 14, '2026-08-10', 'Send September pricing', 'Prefers WhatsApp. Decision maker: Mr. Arora.', '2026-06-15T09:00:00+05:30'),
  ('p-2', 'Surat Textiles', 'Vendor · rain gear', 'vendor', 'con', 'Asia/Kolkata', 7, '2026-08-16', 'Chase revised MOQ', 'Negotiable on advance.', '2026-07-20T09:00:00+05:30'),
  ('p-3', 'Prof. Bianchi', 'Politecnico · supervisor', 'university', 'personal', 'Europe/Rome', 30, NULL, 'Introduce yourself before term', 'Works on interpretability. Read two papers first.', '2026-08-01T09:00:00+05:30'),
  ('p-4', 'R. Mehta', 'Angel · warm intro', 'investor', 'anvik', 'Asia/Kolkata', 21, '2026-07-26', 'Share the traction one-pager', 'Asked about the PD dataset moat.', '2026-07-01T09:00:00+05:30'),
  ('p-5', 'CA Sharma', 'Compliance', 'vendor', 'anvik', 'Asia/Kolkata', 30, '2026-08-13', 'Q2 filings confirmation', '', '2026-06-01T09:00:00+05:30'),
  ('p-6', 'Milan housing agent', 'Relocation', 'personal', 'personal', 'Europe/Rome', 3, '2026-08-17', 'Confirm viewing slot', 'Two flats near Bovisa. Budget €800.', '2026-08-05T09:00:00+05:30')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.people_interactions (id, person_id, occurred_on, summary, logged_by) VALUES
  ('pi-1', 'p-1', '2026-08-10', 'Call — pilot feedback, happy with verdicts', '00000000-0000-4000-8000-000000000001'),
  ('pi-2', 'p-2', '2026-08-16', 'Mail — revised quote promised Friday', '00000000-0000-4000-8000-000000000001'),
  ('pi-3', 'p-4', '2026-07-26', 'Coffee — walked the deck', '00000000-0000-4000-8000-000000000001'),
  ('pi-4', 'p-5', '2026-08-13', 'Mail — GST filed', '00000000-0000-4000-8000-000000000001'),
  ('pi-5', 'p-6', '2026-08-17', 'WhatsApp — sent listings', '00000000-0000-4000-8000-000000000001')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.messages (id, sender_id, body, task_ref_id, attachment_url, song_ref, promoted_to_type, promoted_to_id, created_at) VALUES
  ('msg-1', '00000000-0000-4000-8000-000000000001', 'Pushed the pins on T-42 last night. Need your call before the NIC cutover.', 'T-42', NULL, NULL, NULL, NULL, '2026-08-18T08:41:00+05:30'),
  ('msg-2', '00000000-0000-4000-8000-000000000001', 'Looking now. Also — chai at 4?', NULL, NULL, NULL, NULL, NULL, '2026-08-18T08:56:00+05:30'),
  ('msg-3', '00000000-0000-4000-8000-000000000001', 'Obviously. Surat still hasn''t revised the MOQ, chasing today.', NULL, NULL, NULL, NULL, NULL, '2026-08-18T09:02:00+05:30')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.shared_daily (id, date, song_title, song_artist, song_url, picked_by, photo_url, photo_caption) VALUES
  ('sd-1', '2026-08-18', 'Ilahi', 'Pritam · Arijit Singh', 'https://www.youtube.com/watch?v=UBscsdrK0Bo', '00000000-0000-4000-8000-000000000001', NULL, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.courses (id, title, schedule_label, is_expanded, position) VALUES
  ('crs-1', 'Foundations of machine learning', 'Mon · Wed', true, 1),
  ('crs-2', 'Deep learning systems', 'Tue · Thu', false, 2),
  ('crs-3', 'AI ethics and regulation', 'Fri', false, 3)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.course_items (id, course_id, title, completed, position) VALUES
  ('ci-1', 'crs-1', 'Lecture set 1 notes', true, 1),
  ('ci-2', 'crs-1', 'Problem set 0', true, 2),
  ('ci-3', 'crs-1', 'Reading: attention paper set', false, 3),
  ('ci-4', 'crs-1', 'Problem set 1', false, 4),
  ('ci-5', 'crs-2', 'Environment setup', true, 1),
  ('ci-6', 'crs-2', 'Lab 1 — autograd', false, 2),
  ('ci-7', 'crs-2', 'Reading: systems survey', false, 3),
  ('ci-8', 'crs-3', 'Syllabus review', true, 1),
  ('ci-9', 'crs-3', 'EU AI Act summary', false, 2)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.reading_queue (id, title, author, status, position) VALUES
  ('rd-1', 'Attention Is All You Need', 'Vaswani et al.', 'done', 1),
  ('rd-2', 'Scaling laws — annotated memo', '', 'reading', 2),
  ('rd-3', 'EU AI Act — obligations summary', '', 'queued', 3),
  ('rd-4', 'Interpretability review (Bianchi)', '', 'queued', 4)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.time_logs (id, user_id, date, kind, minutes, course_id) VALUES
  ('tl-1', '00000000-0000-4000-8000-000000000001', '2026-08-17', 'study', 90, 'crs-1'),
  ('tl-2', '00000000-0000-4000-8000-000000000001', '2026-08-17', 'founder', 340, NULL),
  ('tl-3', '00000000-0000-4000-8000-000000000001', '2026-08-16', 'study', 120, 'crs-2'),
  ('tl-4', '00000000-0000-4000-8000-000000000001', '2026-08-16', 'founder', 300, NULL),
  ('tl-5', '00000000-0000-4000-8000-000000000001', '2026-08-15', 'study', 60, 'crs-1'),
  ('tl-6', '00000000-0000-4000-8000-000000000001', '2026-08-15', 'founder', 380, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.life_admin (id, user_id, item, completed, created_at) VALUES
  ('la-1', '00000000-0000-4000-8000-000000000001', 'Renew health insurance before flying', false, '2026-08-01T09:00:00+05:30'),
  ('la-2', '00000000-0000-4000-8000-000000000001', 'Close the Gurugram gym membership', false, '2026-08-01T09:00:00+05:30'),
  ('la-3', '00000000-0000-4000-8000-000000000001', 'Ship winter clothes ahead', false, '2026-08-01T09:00:00+05:30')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.fixed_dates (id, label, date, category) VALUES
  ('fd-1', 'Flight to Milan', '2026-09-12', 'relocation'),
  ('fd-2', 'Term starts — Politecnico', '2026-09-21', 'university'),
  ('fd-3', 'NIC case-number cutover', '2026-09-01', 'business'),
  ('fd-4', 'Enrolment letter upload', '2026-08-25', 'university')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.ledger (id, date, party, category, project_id, direction, amount, status, receipt_url, linked_task_id, import_batch_id) VALUES
  ('lg-1', '2026-08-17', 'Ludhiana Steel', 'Pilot invoice', 'anvik', 'in', 86000, 'paid', NULL, NULL, NULL),
  ('lg-2', '2026-08-16', 'AWS India', 'Infra', 'reg', 'out', 34200, 'paid', NULL, NULL, NULL),
  ('lg-3', '2026-08-15', 'Surat Textiles', 'Sample run', 'con', 'out', 41500, 'overdue', NULL, 'T-47', NULL),
  ('lg-4', '2026-08-14', 'Politecnico Milano', 'Tuition instalment', 'personal', 'out', 210000, 'due', NULL, NULL, NULL),
  ('lg-5', '2026-08-12', 'MCA portal', 'Registry fees', 'reg', 'out', 12800, 'paid', NULL, NULL, NULL),
  ('lg-6', '2026-08-10', 'Contract designer', 'People', 'anvik', 'out', 55000, 'due', NULL, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.audit_trail (id, occurred_at, actor_id, actor_label, entity_type, entity_id, field_name, old_value, new_value, source) VALUES
  ('a-1', '2026-08-17T09:14:00+05:30', '00000000-0000-4000-8000-000000000001', 'Test', 'annotation_pin', 'pin-2', NULL, NULL, 'Pin added on samadhaan_grid.png', 'portal'),
  ('a-2', '2026-08-17T09:12:00+05:30', NULL, 'automated', 'mail_item', 'm-1', 'flag_reason', NULL, 'deadline 1 Sept detected', 'gmail'),
  ('a-3', '2026-08-17T07:30:00+05:30', NULL, 'automated', 'note', 'n-1', NULL, NULL, 'Voice note synced — Vendor call, 14 min', 'plaud'),
  ('a-4', '2026-08-17T07:00:00+05:30', NULL, 'automated', 'digest', 'digest-2026-08-17', NULL, NULL, 'Morning brief emailed to both members', 'gmail'),
  ('a-5', '2026-08-16T18:22:00+05:30', '00000000-0000-4000-8000-000000000001', 'Test', 'ledger', 'batch-0', NULL, NULL, 'Ledger import — 128 rows, 3 duplicates skipped', 'drive'),
  ('a-6', '2026-08-16T11:47:00+05:30', '00000000-0000-4000-8000-000000000001', 'Test', 'task', 'T-42', NULL, NULL, 'Export generated — T-42.md, 2 pins', 'claude_export')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.automation_rules (id, trigger_label, trigger_value, action_label, action_value, is_active, last_fired_at) VALUES
  ('r-1', 'Mail contains a date', 'date-detect', 'Flag in Mail tab', 'flag', true, '2026-08-17T09:12:00+05:30'),
  ('r-2', 'Plaud sync completes', 'plaud-sync', 'Create voice note', 'note', true, '2026-08-17T07:30:00+05:30'),
  ('r-3', 'Daily 07:00 IST', 'cron-0700', 'Send morning digest to both', 'digest', true, '2026-08-17T07:00:00+05:30'),
  ('r-4', 'Task moved to Done', 'task-done', 'Nudge linked ledger entry', 'ledger-nudge', false, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.daily_closeouts (id, user_id, date, shipped, stuck, tomorrow, created_at) VALUES
  ('dc-1', '00000000-0000-4000-8000-000000000001', '2026-08-17', 'Export engine skeleton', 'Fixture drift on golden cases', 'Freeze v3.8', '2026-08-17T21:30:00+05:30')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.day_events (id, user_id, date, start_min, end_min, label, kind, task_id) VALUES
  ('ev-1', '00000000-0000-4000-8000-000000000001', '2026-08-18', 570, 720, 'Build · Registry', 'focus', 'T-42'),
  ('ev-2', '00000000-0000-4000-8000-000000000001', '2026-08-18', 735, 780, 'Admin batch', 'admin', NULL),
  ('ev-3', NULL, '2026-08-18', 960, 990, 'Chai with Raghuvar', 'personal', NULL),
  ('ev-4', '00000000-0000-4000-8000-000000000001', '2026-08-18', 1080, 1170, 'Degree · protected', 'study', NULL),
  ('ev-5', '00000000-0000-4000-8000-000000000001', '2026-08-18', 660, 720, 'Vendor call · Surat', 'meeting', 'T-47')
ON CONFLICT (id) DO NOTHING;
