-- Move the worked example off the two real profiles.
-- Generated by scripts/genReattributeSql.ts. Do not hand-edit.
-- Safe to re-run: every statement is an idempotent UPDATE.
--
-- 0004 attributed the demo content to Anadya and Raghuvar. 0011 was meant to
-- correct that, but its inserts are ON CONFLICT (id) DO NOTHING and 0004 had
-- already claimed those ids — so on any database that ran 0004, 0011 changed
-- nothing and the rows still name a real person as their author. The app
-- hides them from both members (src/lib/demoScope.ts), so this was invisible
-- rather than absent.
--
-- This re-points only the columns that name a person. Row ids and content are
-- untouched, so the demo stays whole under test@anvik.ops and the existing
-- "Remove demo content" purge still matches it by id.
--
-- Scope: the ids below come from seedDataset(), the same manifest purgeDemo.ts
-- uses. Nothing you created in the app can be caught by this — real ids are
-- timestamp-based, these are the seed's literals.
--
-- audit_trail is deliberately NOT rewritten: UPDATE is revoked on it, and a
-- trail that can be retroactively re-attributed is not a trail.

-- tasks: 10 seeded rows
UPDATE public.tasks SET
      created_by = CASE WHEN created_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE created_by END,
      assignee_id = CASE WHEN assignee_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE assignee_id END
 WHERE id IN ('T-47', 'T-46', 'T-45', 'T-44', 'T-42', 'T-41', 'T-40', 'T-38', 'T-36', 'T-30')
   AND (created_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf')
         OR assignee_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- comments: 3 seeded rows
UPDATE public.comments SET
      author_id = CASE WHEN author_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE author_id END
 WHERE id IN ('c-1', 'c-2', 'c-3')
   AND (author_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- screenshot_attachments: 1 seeded row
UPDATE public.screenshot_attachments SET
      uploaded_by = CASE WHEN uploaded_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE uploaded_by END
 WHERE id IN ('shot-1')
   AND (uploaded_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- annotation_pins: 2 seeded rows
UPDATE public.annotation_pins SET
      author_id = CASE WHEN author_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE author_id END
 WHERE id IN ('pin-1', 'pin-2')
   AND (author_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- task_links: 2 seeded rows
UPDATE public.task_links SET
      created_by = CASE WHEN created_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE created_by END
 WHERE id IN ('tl-1', 'tl-2')
   AND (created_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- decisions: 4 seeded rows
UPDATE public.decisions SET
      owner_id = CASE WHEN owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE owner_id END
 WHERE id IN ('dec-1', 'dec-2', 'dec-3', 'dec-4')
   AND (owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- notes: 6 seeded rows
UPDATE public.notes SET
      created_by = CASE WHEN created_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE created_by END,
      owner_id = CASE WHEN owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE owner_id END
 WHERE id IN ('n-1', 'n-2', 'n-3', 'n-4', 'n-5', 'n-6')
   AND (created_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf')
         OR owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- mail_items: 3 seeded rows
UPDATE public.mail_items SET
      owner_id = CASE WHEN owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE owner_id END
 WHERE id IN ('m-1', 'm-2', 'm-3')
   AND (owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- documents: 8 seeded rows
UPDATE public.documents SET
      owner_id = CASE WHEN owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE owner_id END
 WHERE id IN ('doc-1', 'doc-2', 'doc-3', 'doc-4', 'doc-5', 'doc-6', 'doc-7', 'doc-8')
   AND (owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- pages: 2 seeded rows
UPDATE public.pages SET
      created_by = CASE WHEN created_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE created_by END,
      last_edited_by = CASE WHEN last_edited_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE last_edited_by END,
      owner_id = CASE WHEN owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE owner_id END
 WHERE id IN ('pg-1', 'pg-2')
   AND (created_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf')
         OR last_edited_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf')
         OR owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- page_comments: 1 seeded row
UPDATE public.page_comments SET
      author_id = CASE WHEN author_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE author_id END,
      resolved_by = CASE WHEN resolved_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE resolved_by END
 WHERE id IN ('pc-1')
   AND (author_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf')
         OR resolved_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- people_interactions: 5 seeded rows
UPDATE public.people_interactions SET
      logged_by = CASE WHEN logged_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE logged_by END
 WHERE id IN ('pi-1', 'pi-2', 'pi-3', 'pi-4', 'pi-5')
   AND (logged_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- messages: 3 seeded rows
UPDATE public.messages SET
      sender_id = CASE WHEN sender_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE sender_id END
 WHERE id IN ('msg-1', 'msg-2', 'msg-3')
   AND (sender_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- shared_daily: 1 seeded row
UPDATE public.shared_daily SET
      picked_by = CASE WHEN picked_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE picked_by END
 WHERE id IN ('sd-1')
   AND (picked_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- courses: 3 seeded rows
UPDATE public.courses SET
      owner_id = CASE WHEN owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE owner_id END
 WHERE id IN ('crs-1', 'crs-2', 'crs-3')
   AND (owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- reading_queue: 4 seeded rows
UPDATE public.reading_queue SET
      owner_id = CASE WHEN owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE owner_id END
 WHERE id IN ('rd-1', 'rd-2', 'rd-3', 'rd-4')
   AND (owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- time_logs: 6 seeded rows
UPDATE public.time_logs SET
      user_id = CASE WHEN user_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE user_id END
 WHERE id IN ('tl-1', 'tl-2', 'tl-3', 'tl-4', 'tl-5', 'tl-6')
   AND (user_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- life_admin: 3 seeded rows
UPDATE public.life_admin SET
      user_id = CASE WHEN user_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE user_id END
 WHERE id IN ('la-1', 'la-2', 'la-3')
   AND (user_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- fixed_dates: 4 seeded rows
UPDATE public.fixed_dates SET
      owner_id = CASE WHEN owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE owner_id END
 WHERE id IN ('fd-1', 'fd-2', 'fd-3', 'fd-4')
   AND (owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- ledger: 6 seeded rows
UPDATE public.ledger SET
      paid_by = CASE WHEN paid_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE paid_by END
 WHERE id IN ('lg-1', 'lg-2', 'lg-3', 'lg-4', 'lg-5', 'lg-6')
   AND (paid_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- daily_closeouts: 1 seeded row
UPDATE public.daily_closeouts SET
      user_id = CASE WHEN user_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE user_id END
 WHERE id IN ('dc-1')
   AND (user_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- day_events: 5 seeded rows
UPDATE public.day_events SET
      user_id = CASE WHEN user_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE user_id END
 WHERE id IN ('ev-1', 'ev-2', 'ev-3', 'ev-4', 'ev-5')
   AND (user_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- personal_goals: 2 seeded rows
UPDATE public.personal_goals SET
      user_id = CASE WHEN user_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE user_id END
 WHERE id IN ('pg-goal-1', 'pg-goal-2')
   AND (user_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- mood_items: 2 seeded rows
UPDATE public.mood_items SET
      user_id = CASE WHEN user_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE user_id END
 WHERE id IN ('mood-1', 'mood-2')
   AND (user_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- subscriptions: 3 seeded rows
UPDATE public.subscriptions SET
      paid_by = CASE WHEN paid_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE paid_by END
 WHERE id IN ('sub-1', 'sub-2', 'sub-3')
   AND (paid_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- tags: 6 seeded rows
UPDATE public.tags SET
      created_by = CASE WHEN created_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') THEN '00000000-0000-4000-8000-000000000001'::uuid ELSE created_by END
 WHERE id IN ('tag-1', 'tag-2', 'tag-3', 'tag-4', 'tag-5', 'tag-6')
   AND (created_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'));

-- The demo mail also carried a real account address on it.
UPDATE public.mail_items
   SET account_email = 'test@anvik.ops'
 WHERE id IN ('m-1', 'm-2', 'm-3')
   AND account_email IN ('anvik.anadya@gmail.com', 'raghuvar.anvik@gmail.com');

-- ═══ Confirm ══════════════════════════════════════════════════════════
-- Every count should be 0. Anything above 0 is a seeded row still naming a
-- real person, and means this migration did not cover that column.
SELECT 'tasks' AS table_name, count(*) AS still_real FROM public.tasks
 WHERE id IN ('T-47', 'T-46', 'T-45', 'T-44', 'T-42', 'T-41', 'T-40', 'T-38', 'T-36', 'T-30')
   AND (created_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') OR assignee_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'))
UNION ALL
SELECT 'notes', count(*) FROM public.notes
 WHERE id IN ('n-1', 'n-2', 'n-3', 'n-4', 'n-5', 'n-6')
   AND (created_by IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf') OR owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf'))
UNION ALL
SELECT 'mail_items', count(*) FROM public.mail_items
 WHERE id IN ('m-1', 'm-2', 'm-3')
   AND (owner_id IN ('6929a827-f871-4c9a-b6bb-367b823b16b3', '78e2346f-632f-4928-aeb7-857ec7b751bf')
        OR account_email IN ('anvik.anadya@gmail.com', 'raghuvar.anvik@gmail.com'));
