-- Free-form task type; remove the seeded worked example, projects included.
-- Generated by scripts/genFreeVocabSql.ts. Do not hand-edit.
-- Safe to re-run: every DELETE is by literal id, every ALTER is idempotent.
--
-- Task type stops being a 4-value CHECK and becomes free text with a length
-- cap, matching every other open vocabulary in the app. 'ops' and
-- 'code_change' still unlock their special task-page panels when a task
-- happens to carry that exact string — nothing requires it to any more.
--
-- The seeded demo — including the 4 project rows it invented (Anvik,
-- Registry, Consumer, Personal) — is deleted outright rather than merely
-- hidden. Confirmed before writing this migration: exactly 10 tasks exist on
-- the live database and all 10 are seed ids, so nothing real is touched.
-- src/data/seed.ts is untouched — local mock-mode dev still gets the full
-- demo, only the live database's copy of it is gone.

-- ═══ Task type: enum → free text with a length cap ═════════════════════
ALTER TABLE public.tasks DROP CONSTRAINT IF EXISTS tasks_type_check;
ALTER TABLE public.tasks DROP CONSTRAINT IF EXISTS cap_tasks_type;
ALTER TABLE public.tasks ADD CONSTRAINT cap_tasks_type
  CHECK (type IS NOT NULL AND char_length(type) <= 60);

-- ═══ Remove the seeded worked example ═══════════════════════════════════
DELETE FROM public.annotation_pins WHERE id IN ('pin-1', 'pin-2');
DELETE FROM public.screenshot_attachments WHERE id IN ('shot-1');
DELETE FROM public.comments WHERE id IN ('c-1', 'c-2', 'c-3');
DELETE FROM public.subtasks WHERE id IN ('st-1', 'st-2', 'st-3', 'st-4', 'st-5', 'st-6', 'st-7');
DELETE FROM public.task_links WHERE id IN ('tl-1', 'tl-2');
DELETE FROM public.day_events WHERE id IN ('ev-1', 'ev-2', 'ev-3', 'ev-4', 'ev-5');
DELETE FROM public.tasks WHERE id IN ('T-47', 'T-46', 'T-45', 'T-44', 'T-42', 'T-41', 'T-40', 'T-38', 'T-36', 'T-30');
DELETE FROM public.time_logs WHERE id IN ('tl-1', 'tl-2', 'tl-3', 'tl-4', 'tl-5', 'tl-6');
DELETE FROM public.key_results WHERE id IN ('kr-1', 'kr-2', 'kr-3', 'kr-4', 'kr-5', 'kr-6', 'kr-7', 'kr-8', 'kr-9', 'kr-10');
DELETE FROM public.objectives WHERE id IN ('okr-reg', 'okr-score', 'okr-con', 'okr-italy');
DELETE FROM public.course_items WHERE id IN ('ci-1', 'ci-2', 'ci-3', 'ci-4', 'ci-5', 'ci-6', 'ci-7', 'ci-8', 'ci-9');
DELETE FROM public.courses WHERE id IN ('crs-1', 'crs-2', 'crs-3');
DELETE FROM public.page_comments WHERE id IN ('pc-1');
DELETE FROM public.pages WHERE id IN ('pg-1', 'pg-2');
DELETE FROM public.people_interactions WHERE id IN ('pi-1', 'pi-2', 'pi-3', 'pi-4', 'pi-5');
DELETE FROM public.people WHERE id IN ('p-1', 'p-2', 'p-3', 'p-4', 'p-5', 'p-6');
DELETE FROM public.mail_items WHERE id IN ('m-1', 'm-2', 'm-3');
DELETE FROM public.notes WHERE id IN ('n-1', 'n-2', 'n-3', 'n-4', 'n-5', 'n-6');
-- One stray real row, not from the seed: a note titled "hello" created under
-- the test account (00000000-0000-4000-8000-000000000001), referencing the
-- 'anvik' project. Discovered when the first run of this migration failed on
-- the FK below — swept for by hand rather than by id list, since it isn't a
-- seed row. Not Anadya's or Raghuvar's: created_by confirmed test-account
-- before this line was added.
DELETE FROM public.notes WHERE id = 'n-mszoj2xu2' AND created_by = '00000000-0000-4000-8000-000000000001';
DELETE FROM public.decisions WHERE id IN ('dec-1', 'dec-2', 'dec-3', 'dec-4');
DELETE FROM public.documents WHERE id IN ('doc-1', 'doc-2', 'doc-3', 'doc-4', 'doc-5', 'doc-6', 'doc-7', 'doc-8');
DELETE FROM public.messages WHERE id IN ('msg-1', 'msg-2', 'msg-3');
DELETE FROM public.shared_daily WHERE id IN ('sd-1');
DELETE FROM public.reading_queue WHERE id IN ('rd-1', 'rd-2', 'rd-3', 'rd-4');
DELETE FROM public.life_admin WHERE id IN ('la-1', 'la-2', 'la-3');
DELETE FROM public.fixed_dates WHERE id IN ('fd-1', 'fd-2', 'fd-3', 'fd-4');
DELETE FROM public.ledger WHERE id IN ('lg-1', 'lg-2', 'lg-3', 'lg-4', 'lg-5', 'lg-6');
DELETE FROM public.automation_rules WHERE id IN ('r-1', 'r-2', 'r-3', 'r-4');
DELETE FROM public.daily_closeouts WHERE id IN ('dc-1');
DELETE FROM public.pulse_items WHERE id IN ('pulse-1', 'pulse-2', 'pulse-3');

-- ═══ The 4 seeded projects, now unreferenced ════════════════════════════
DELETE FROM public.projects WHERE id IN ('anvik', 'reg', 'con', 'personal');

-- ═══ Confirm ═════════════════════════════════════════════════════════
-- Every count should be 0.
SELECT 'tasks' AS table_name, count(*) AS remaining FROM public.tasks
UNION ALL SELECT 'projects', count(*) FROM public.projects WHERE id IN ('anvik', 'reg', 'con', 'personal')
UNION ALL SELECT 'type_check_is_enum', count(*) FROM pg_constraint
  WHERE conrelid = 'public.tasks'::regclass AND conname = 'tasks_type_check';
